[tools]
python = "3.12"
uv = "latest"

[settings]
experimental = true
fetch_remote_versions_timeout = "30"
python_compile = false

[env]
_.python.venv = { path = ".venv", create = true }

[hooks]
postinstall = [
  "git lfs install --local",
  "git lfs pull",
  "uv pip install -e .",
]

[tasks.test]
dir = "tests"
run = [
  "test -d build.tmp || meson setup build.tmp",
  "ninja -C build.tmp test",
]

[tasks.tag]
run = [
  "git pull",
  "git tag -a v{{arg(name='version')}} -m 'Version {{arg(name='version')}}'",
  "git push --tags",
]
